### ISSUE TITLE
Cant figure out how to append to an existing file, need help!

### ISSUE THREAD

**Issue by timohahaa** [fumiama/go-docx#13]
I try to append new text to an existing docx file like this:
```go
readFile, err := os.Open(filename)
if err != nil {
	// ...
}
fileinfo, err := readFile.Stat()
if err != nil {
	//...
}
size := fileinfo.Size()
oldDoc, err := docx.Parse(readFile, size)
if err != nil {
	//...
}
doc := docx.LoadBodyItems(oldDoc.Document.Body.Items, []docx.Media{})
p := doc.AddParagraph()
p.AddText(text).Size("10")
if err != nil {
	//...
}
_, err = doc.WriteTo(readFile)
if err != nil {
	//...
}
err = readFile.Close()
if err != nil {
	//...
}
```

but it just adds new content and erases the old file...

It also seems to ignore '\n' in the text - no new lines are made, how do I insert a new line?

**Comment by fumiama** [comment]
The issue is because that you used the `LoadBodyItems` function, which will clear the doc file. Actually I have written a function named `func (f *Docx) AppendFile(af *Docx)` for the file-appending. You can refer to the last few lines of the file `structdoc.go`.

**Comment by fumiama** [comment]
As for the `\n`, it is ignored by Word because it is replaced by just adding a new paragraph.

**Comment by timohahaa** [comment]
Thanks for the help!
