### ISSUE TITLE
A3模板以及分页符

### ISSUE THREAD

**Issue by mabiao0525** [fumiama/go-docx#17]
请问现在有可以更换A4为A3的调用吗，以及是否可以添加分页符？

**Comment by fumiama** [comment]
你可以发一个PR.

**Comment by mabiao0525** [comment]
你好，目前关于A3模板我进行了2种方法的测试，不过都出现了一些问题：
1.新建了空白A3word文档，并将相关文件考入，使用UseTemplate函数，但是在执行到WriteTo时会出现panic: open xml/a3/_rels/.rels: file does not exist提示，图中是我当前的测试代码，以及项目树
![Snipaste_2024-03-15_11-19-58](https://github.com/fumiama/go-docx/assets/70356026/a05e6956-854c-4b34-9ea0-a42db728afc5)
`package main

import (
	"embed"
	"os"

	"github.com/fumiama/go-docx"
)

var (
	//go:embed xml
	//go:embed xml/a3/_rels/*
	templateFS embed.FS

	// a3TemplateFilesList is the files list under templateFS/xml/a3
	a3TemplateFilesList = []string{
		"_rels/.rels",
		"docProps/app.xml",
		"docProps/core.xml",
		"word/theme/theme1.xml",
		"word/fontTable.xml",
		"word/styles.xml",
		"[Content_Types].xml",
	}
)

func main() {
	w := docx.NewA4()
	w.UseTemplate("a3", a3TemplateFilesList, templateFS)
	w.AddParagraph().AddText("test")

	result, err := os.Create("result.docx")
	// save to file
	if err != nil {
		panic(err)
	}
	_, err = w.WriteTo(result)
	if err != nil {
		panic(err)
	}
	err = result.Close()
	if err != nil {
		panic(err)
	}

}
`
不知道是不是我的使用有问题，想问下如何正确使用，是否可以出一个UseTemplate的说明

2.下载源码，直接用A3格式相关文档替换原xml/a4中的文件，运行后，可以生成文件，但是打开文件会显示
![1](https://github.com/fumiama/go-docx/assets/70356026/82e4a334-0fbd-4573-a93b-3c062dbe839b)
点击确定后，打开仍为A4模板，想问下有无解决办法

**Comment by fumiama** [comment]
抱歉，看来是我判断错误了，A4 A3的判定应该在`docyments.xml`，由以下语句控制(A3的情况)
```xml
<w:sectPr w:rsidR="00384B6B" w:rsidSect="00654812">
    <w:pgSz w:w="16840" w:h="23820"/>
    <w:pgMar w:top="1440" w:right="1800" w:bottom="1440" w:left="1800" w:header="851" w:footer="992" w:gutter="0"/>
    <w:cols w:space="425"/>
    <w:docGrid w:type="lines" w:linePitch="312"/>
</w:sectPr>
```

**Comment by fumiama** [comment]
关于这个，我可以改，但最近没时间，你要急用的话可以自己改一下，然后另行提交PR。我已经推送了一个新版本，将令人迷惑的`NewA4()`替换了。

**Comment by mabiao0525** [comment]
谢谢，请问你有什么思路吗，因为我看在wirteTo中的pack函数时会把document.xml.rels和document.xml覆盖掉

**Comment by mabiao0525** [comment]
已经完成，提交了PR，请查收

**Comment by fumiama** [comment]
> 谢谢，请问你有什么思路吗，因为我看在wirteTo中的pack函数时会把document.xml.rels和document.xml覆盖掉

就按你那样就可以了，建议封装一些新的函数方便切换页面大小。
```go
func (f *Docx) WithA4Page()
func (f *Docx) WithA3Page()
```

**Comment by mabiao0525** [comment]
已完成
