### ISSUE TITLE
code issue

### ISSUE THREAD

**Issue by xiaohei417** [fumiama/go-docx#30]
I want to add watermark or open file template re-write new file.

**Comment by xiaohei417** [comment]
I want to read `xxx.docx` and write some text for `xxx.docx`, but no change after re-open file.
please help check code, thanks.

```
package main

import (
	"fmt"
	"os"

	"github.com/fumiama/go-docx"
)

func main() {
	readFile, err := os.Open("xxx.docx")
	if err != nil {
		panic(err)
	}
	fileinfo, err := readFile.Stat()
	if err != nil {
		panic(err)
	}
	size := fileinfo.Size()
	doc, err := docx.Parse(readFile, size)
	if err != nil {
		panic(err)
	}
	
	d := docx.LoadBodyItems(doc.Document.Body.Items, nil)
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	d.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
	_, err = d.WriteTo(readFile)
	if err != nil {
		panic(err)
	}
	
	fmt.Println("Plain text:")
	for _, it := range d.Document.Body.Items {
		switch it.(type) {
		case *docx.Paragraph, *docx.Table: // printable
			fmt.Println(it)
		}
	}
}
```

**Comment by xiaohei417** [comment]
![image](https://github.com/fumiama/go-docx/assets/41576095/208efbc5-c191-43e1-8ebf-8e9603302acc)

**Comment by fumiama** [comment]
说明你的docx中包含一些本库尚未完全支持的内容。详见 #26

**Comment by xiaohei417** [comment]
> 说明你的docx中包含一些本库尚未完全支持的内容。详见 #26

but my `docx file` only several lines text

**Comment by fumiama** [comment]
> > 说明你的docx中包含一些本库尚未完全支持的内容。详见 #26
> 
> but my `docx file` only several lines text, my computer is mac intel

可以发一下你的文件链接，我有空试试。

**Comment by xiaohei417** [comment]
> > > 说明你的docx中包含一些本库尚未完全支持的内容。详见 #26
> > 
> > 
> > but my `docx file` only several lines text, my computer is mac intel
> 
> 可以发一下你的文件链接，我有空试试。

[xxx.docx](https://github.com/fumiama/go-docx/files/15272016/xxx.docx)

**Comment by xiaohei417** [comment]
@fumiama 请问您那边尝试是否有问题？

**Comment by willthrom** [comment]
Hi @fumiama 
I think I have the same problem.
I even went further, go to https://www.microsoft365.com/?auth=1 create a blank empty word docx document. 
I download it, then run a simple test, parse and write, the new file is not working in Microsoft Word or Google Word.
I can open it with WordPad thought.

Here it is the code:
`func main() {
	readFile, err := os.Open("blank.docx")
	if err != nil {
		panic(err)
	}
	fileinfo, err := readFile.Stat()
	if err != nil {
		panic(err)
	}
	size := fileinfo.Size()
	doc, err := docx.Parse(readFile, size)
	if err != nil {
		panic(err)
	}
	fmt.Println("Plain text:")

	f, err := os.Create("xxx3.docx")
	if err != nil {
		panic(err)
	}

	_, err = doc.WriteTo(f)
	if err != nil {
		panic(err)
	}
	f.Close()
}
`

Source file: 
[blank.docx](https://github.com/fumiama/go-docx/files/15485108/blank.docx)
Generated file:
[xxx3.docx](https://github.com/fumiama/go-docx/files/15485112/xxx3.docx)

**Comment by willthrom** [comment]
I did took a look to the doc document and the items after testing with unidoc what happened after reading/writting the file. Unidoc created lots of sections.

If I check for the last item in my generated document and remove the last one, if it is a sections, the word generate is valid and readable by Microsoft Office

// Sections seems to have a bug, so we need to remove the last 1 item if it is a section
	// interface {}(*github.com/fumiama/go-docx.SectPr) *{XMLName: encoding/xml.Name {Space: "", Local: ""}, PgSz: *github.com/fumiama/go-docx.PgSz {W: (*"encoding/xml.Attr")(0xc000234780), H: (*"encoding/xml.Attr")(0xc0002347b0)}}
	if len(doc.Document.Body.Items) > 0 {
		if _, ok := doc.Document.Body.Items[len(doc.Document.Body.Items)-1].(*docx.SectPr); ok {
			doc.Document.Body.Items = doc.Document.Body.Items[:len(doc.Document.Body.Items)-1]
		}
	}

**Comment by willthrom** [comment]
Closes as not planned? 
As mentioned, this library in its current states doesn't generate properly documents to be read by the Latest version of Microsoft Office.

When the library parser a document, If there is a "section" component (which they are always in Microsoft Office 365), it is adding an extra item with not well formatted XML parameters. PageW

The word generated is not working and that is the reason if I remove the last Item in the body it works in Microsoft Office 365.

We had to add this to our code after parsing the doc.

![image](https://github.com/user-attachments/assets/592de247-2ac0-4582-b4a5-646f1e12de55)

**Comment by fumiama** [comment]
I would like to solve it, but recently I do not have time to debug. This issue is closed by its author, but I will still fix this problem when I am free. Since you have pointed out the real problem, I will try to fix that.

**Comment by willthrom** [comment]
Thanks @fumiama , I will try to help you when I have some free time . providing the exact header for the section failing.

**Comment by fumiama** [comment]
> Hi @fumiama I think I have the same problem. I even went further, go to https://www.microsoft365.com/?auth=1 create a blank empty word docx document. I download it, then run a simple test, parse and write, the new file is not working in Microsoft Word or Google Word. I can open it with WordPad thought.
> 
> Here it is the code:
> 
> ```go
> func main() {
> 	readFile, err := os.Open("blank.docx")
> 	if err != nil {
> 		panic(err)
> 	}
> 	fileinfo, err := readFile.Stat()
> 	if err != nil {
> 		panic(err)
> 	}
> 	size := fileinfo.Size()
> 	doc, err := docx.Parse(readFile, size)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	f, err := os.Create("xxx3.docx")
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	_, err = doc.WriteTo(f)
> 	if err != nil {
> 		panic(err)
> 	}
> 	f.Close()
> }
> ```
> 
> Source file: [blank.docx](https://github.com/fumiama/go-docx/files/15485108/blank.docx) Generated file: [xxx3.docx](https://github.com/fumiama/go-docx/files/15485112/xxx3.docx)

This blank test seems OK.

**Comment by fumiama** [comment]
> 我稍微调整了一下代码，出现了新的错误
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"os"
> 
> 	"github.com/fumiama/go-docx"
> )
> 
> func main() {
> 	readFile, err := os.Open("xxx.docx")
> 	if err != nil {
> 		panic(err)
> 	}
> 	fileinfo, err := readFile.Stat()
> 	if err != nil {
> 		panic(err)
> 	}
> 	size := fileinfo.Size()
> 	doc, err := docx.Parse(readFile, size)
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 	doc.AddParagraph().AddText("ashfjklhsjakdhfkhas").Size("20")
> 
> 	fmt.Println("Plain text:")
> 	for _, it := range doc.Document.Body.Items {
> 		switch it.(type) {
> 		case *docx.Paragraph, *docx.Table: // printable
> 			fmt.Println(it)
> 		}
> 	}
> 
> 	f, err := os.Create("xxx2.docx")
> 	if err != nil {
> 		panic(err)
> 	}
> 
> 	_, err = doc.WriteTo(f)
> 	if err != nil {
> 		panic(err)
> 	}
> 	f.Close()
> }
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/41576095/329183002-208efbc5-c191-43e1-8ebf-8e9603302acc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Nzc2MzUsIm5iZiI6MTcyNjU3NzMzNSwicGF0aCI6Ii80MTU3NjA5NS8zMjkxODMwMDItMjA4ZWZiYzUtYzE5MS00M2UxLThlYmYtOGU5NjAzMzAyYWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDEyNDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMTEyNGU5NzdmZjVlY2UzNjhkMGRkODNlMjBkMGEzN2U2Mzg4YmMyNzEzNGNiN2NhN2ZmMjIyMDg4NjE4OTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMtFbqJShKja98poCk66fuSM-JTfAC7yGvIkX4nStag)

我使用最新代码和你的`xxx.docx`测试，一切正常。

**Comment by willthrom** [comment]
Microsoft Office Online 365
![image](https://github.com/user-attachments/assets/64465f49-e2b1-4636-a75d-698f186c7f77)
Download file
[TestDocx 1.docx](https://github.com/user-attachments/files/17175614/TestDocx.1.docx)
Manipulating file open and save:
`	// Write the file as a copy the original file with just .back
	name := "godup_" + "test" + ".docx"
	f, err := os.Create(name)
	if err != nil {
		panic(err)
	}

	// Save the modified document to a new file
	_, err = doc.WriteTo(f)

	// Close the file
	f.Close()`
	
End result file:
[godup_test.docx](https://github.com/user-attachments/files/17175622/godup_test.docx)

Trying to open the file in Microsoft Office

![image](https://github.com/user-attachments/assets/a623f04d-c306-4290-841a-b643fd215c01)


But if before saving the file I remove the last child:

`// Sections seems to have a bug, so we need to remove the last 1 item if it is a section
	// interface {}(*github.com/fumiama/go-docx.SectPr) *{XMLName: encoding/xml.Name {Space: "", Local: ""}, PgSz: *github.com/fumiama/go-docx.PgSz {W: (*"encoding/xml.Attr")(0xc000234780), H: (*"encoding/xml.Attr")(0xc0002347b0)}}
	if len(doc.Document.Body.Items) > 0 {
		if _, ok := doc.Document.Body.Items[len(doc.Document.Body.Items)-1].(*docx.SectPr); ok {
			doc.Document.Body.Items = doc.Document.Body.Items[:len(doc.Document.Body.Items)-1]
		}
	}`

The written file works flawless

**Comment by willthrom** [comment]
I can see in the final file this section:

`                <w:sectPr>
			<w:pgSz w:w="11906" w:w="16838"/>
		</w:sectPr>`

which is the one I removed after parsing so when I write the file, the file open successfully, if I leave it, it doesn't with the error in my previous message.

`// Sections seems to have a bug, so we need to remove the last 1 item if it is a section
	// interface {}(*github.com/fumiama/go-docx.SectPr) *{XMLName: encoding/xml.Name {Space: "", Local: ""}, PgSz: *github.com/fumiama/go-docx.PgSz {W: (*"encoding/xml.Attr")(0xc000234780), H: (*"encoding/xml.Attr")(0xc0002347b0)}}
	if len(doc.Document.Body.Items) > 0 {
		if _, ok := doc.Document.Body.Items[len(doc.Document.Body.Items)-1].(*docx.SectPr); ok {
			doc.Document.Body.Items = doc.Document.Body.Items[:len(doc.Document.Body.Items)-1]
		}
	}
`

The originals section in my source file is:

`<w:sectPr>
			<w:headerReference r:id="rId7" w:type="default"/>
			<w:headerReference r:id="rId8" w:type="first"/>
			<w:headerReference r:id="rId9" w:type="even"/>
			<w:footerReference r:id="rId10" w:type="default"/>
			<w:footerReference r:id="rId11" w:type="first"/>
			<w:footerReference r:id="rId12" w:type="even"/>
			<w:pgSz w:h="16838" w:w="11906" w:orient="portrait"/>
			<w:pgMar w:bottom="1134" w:top="1417" w:left="1701" w:right="991" w:header="426" w:footer="272"/>
			<w:pgNumType w:start="1"/>
		</w:sectPr>`
		
But if focus in the [w:pgSz w:h] tag

source was w:h, when destination is w:w

w:pgSz w:h="16838" w:w="11906"
w:pgSz w:w="11906" w:w="16838"

**Comment by willthrom** [comment]
I just took a look to your last version of the code, which is not what I was running and you fixed this a month ago...

![image](https://github.com/user-attachments/assets/6c5b2a80-c004-4dc5-bd9b-c047221ca5f9)

**Comment by fumiama** [comment]
> I just took a look to your last version of the code, which is not what I was running and you fixed this a month ago...
> 
> ![image](https://private-user-images.githubusercontent.com/2103849/371841392-6c5b2a80-c004-4dc5-bd9b-c047221ca5f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjEzOTEsIm5iZiI6MTcyNzc2MTA5MSwicGF0aCI6Ii8yMTAzODQ5LzM3MTg0MTM5Mi02YzViMmE4MC1jMDA0LTRkYzUtYmQ5Yi1jMDQ3MjIxY2E1ZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDFUMDUzODExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWMyNzE1N2VkZDg2MGUzYTc0MjliYTA0YWRhM2YzNGE2NzFiNjRmMTc3M2Y0YWM0Y2VlMGE3ZTEwNzIzYjFjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2d2FR6UhzVbx1BVCTa8rKkmihiBytnYiCDEkgOHUcm8)

I haven't introduce the version tag because this lib is not stable enough. But happy to see that your problem solved.
