### ISSUE TITLE
Hellow, how can i add text to existing file and save this later with changes?

### ISSUE THREAD

**Issue by Ada-lave** [fumiama/go-docx#35]
i try use this code 
```go
       f, err := os.Create("generated.docx")

	if err != nil {
		panic(err)
	}
	doc := docx.New()
	doc.AppendFile(ED.Doc) // *docx.Docx
	_, err = doc.WriteTo(f)
	if err != nil {
		panic(err)
	}
	err = f.Close()
	if err != nil {
		panic(err)
	}
```

But i got error from Word "Cant open this file"

**Comment by Ada-lave** [comment]
I also noticed that if you open it using LibreOffice, it can restore it, but Word can't

**Comment by Ada-lave** [comment]
I also noticed a curious thing: the *docx.AppendFile function works fine with files that are created by the library, but if we use an empty file generated by Word 2021, it breaks. Additionally, the size of an empty Word file created by ourselves is 12 KB, while the size of a file created by the library is only 9 KB.

**Comment by fumiama** [comment]
> I also noticed that if you open it using LibreOffice, it can restore it, but Word can't

There're some additional checks in Word. It's hard to fit all cases by myself.

> I also noticed a curious thing: the *docx.AppendFile function works fine with files that are created by the library, but if we use an empty file generated by Word 2021, it breaks.

Maybe because there're some unsupported elements in the file that generated by Word of that version.

**Comment by Ada-lave** [comment]
When I unzip the lib docx file and the Word docx file, I found this difference: the Word docx file has docx/settings.yml and docx/web-settings.yml, but the lib Docx file doesn't have these.

**Comment by fumiama** [comment]
> the Word docx file has docx/settings.yml and docx/web-settings.yml, but the lib Docx file doesn't have these.

I tested these files and found that it's ok to remove them, so I did.

**Comment by Ada-lave** [comment]
Thanks you, i test it today

**Comment by Ada-lave** [comment]
I found what the problem, its happens after i save docx file using code like this
```go
func (ED *EvertDoc) SaveFormattedDoc() {
	f, err := os.Create("generated.docx")

	if err != nil {
		panic(err)
	}
	_, err = ED.Doc.WriteTo(f)
	if err != nil {
		panic(err)
	}
	err = f.Close()
	if err != nil {
		panic(err)
	}
}
```
after i save using this method in my word/document.xml i get parameter <w:pgSz w:w="11906" w:w="16838"/> but it will be <w:pgSz w:w="11906" w:h="16838"/>, and now i dont know how to fix it

**Comment by fumiama** [comment]
Thanks, fixed, please try the latest.

**Comment by Ada-lave** [comment]
Now it really works! Thanks you!
