### ISSUE TITLE
可以设置页面方向为横向吗？

### ISSUE THREAD

**Issue by iTanken** [fumiama/go-docx#4]
你好，看了下代码，没有找到设置页面方向 portrait、landscape 相关的代码。

请问可以设置页面方向为横向或者考虑支持吗？

**Comment by fumiama** [comment]
横向页面涉及到页面属性，并不是更改页面内容能够解决的，你需要更改页面模版。目前本库只有一个模版，即纵向A4，位于`xml/a4`，但是你也可以自定义其他模版，使用`docf.UseTemplate()`进行替换。

**Comment by iTanken** [comment]
> 横向页面涉及到页面属性，并不是更改页面内容能够解决的，你需要更改页面模版。目前本库只有一个模版，即纵向A4，位于`xml/a4`，但是你也可以自定义其他模版，使用`docf.UseTemplate()`进行替换。

好的，谢谢
