### ISSUE TITLE
Any guideline how I could add support for for Header and Footer

### ISSUE THREAD

**Issue by willthrom** [fumiama/go-docx#41]
Hi,

right now I am reading some word documents where I could like to just add some text to the main body (actually it is a search and replace functinality I have already working (placeholder substitution).

However I noticed header/footers is not there...  not copied from the original final to the destination.

I was thinking just to add a copy whatever is there.. no need to really understand it... all those XML.....

**Comment by fumiama** [comment]
> I was thinking just to add a copy whatever is there.. no need to really understand it...

That's what I'm doing. You can unpack the docx file as a zip, look into `document.xml` and figure out the OpenXML representation of header and footer, then add them to this repo by imitating the codes existing.

**Comment by willthrom** [comment]
> > I was thinking just to add a copy whatever is there.. no need to really understand it...
> 
> That's what I'm doing. You can unpack the docx file as a zip, look into `document.xml` and figure out the OpenXML representation of header and footer, then add them to this repo by imitating the codes existing.

It is true you store all the files from the zip in the new "zip", like all the header/footers/etc but I took a look and it seems your current parser of document.xml removed everything doesn't understand, so it need to be put it back, like the headers information, in a specific order... no easy task...

**Comment by fumiama** [comment]
Yes. If you just want to modify a few words, this package may not be suitable for you because it will only handle the structures that it understand because we aims to construct a minimal realization.

**Comment by willthrom** [comment]
I will try add support for headers to this library if I find some spare time.
For the time being, thanks for the package!, very useful.

Cheers
